remote_theme: affiliates-jekyll-theme


title: "SCI-T"
email: wowthemesnet@gmail.com
timezone: UTC
baseurl: "/affiliates-jekyll-theme"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/sal.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://x.com/scit162223
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  Juan David de los Rios Mahecha:
    name: Juan David de los Rios Mahecha
    display_name: Juan David de los Rios Mahecha
    avatar: 'assets/images/JuanDaviddelosRiosMahecha_PERF.jpeg'
    email: juan.delosriosdv@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://x.com/juandelosrios21
    description: "Founder of SCI-T, physics student at the Francisco Jose de Caldas District University, Bogota-Colombia"

  sci-t.education:
    name: sci-t.education
    display_name: SCI-T education
    avatar: 'assets/images/JuanDaviddelosRiosMahecha_PERF.jpeg'
    email: juan.delosriosdv@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://x.com/juandelosrios21
    description: "SCI-T recommended education"

# Social
social:
  instagram: https://www.instagram.com/scti.ceo/
  facebook: https://www.facebook.com/profile.php?id=61569444091031
  twitter: https://x.com/scit162223

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
